memcg-v1-no-need-for-memcg-locking-for-mglru-fix
remove now-unused local:

mm/vmscan.c: In function 'walk_mm':
mm/vmscan.c:3652:28: error: unused variable 'memcg' [-Werror=unused-variable]
 3652 |         struct mem_cgroup *memcg = lruvec_memcg(lruvec);
      |                            ^~~~~
Cc: Hugh Dickins <hughd@google.com>
Cc: Johannes Weiner <hannes@cmpxchg.org>
Cc: Michal Hocko <mhocko@suse.com>
Cc: Muchun Song <muchun.song@linux.dev>
Cc: Roman Gushchin <roman.gushchin@linux.dev>
Cc: Shakeel Butt <shakeel.butt@linux.dev>
Cc: Yosry Ahmed <yosryahmed@google.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>