mmtmpfs-consider-end-of-file-write-in-shmem_is_huge-checkpatch-fixes
ERROR: code indent should use tabs where possible
#215: FILE: mm/shmem.c:1676:
+^I^I       ^I^I^I^Ishmem_huge_force, vma, vm_flags);$

WARNING: please, no space before tabs
#215: FILE: mm/shmem.c:1676:
+^I^I       ^I^I^I^Ishmem_huge_force, vma, vm_flags);$

ERROR: code indent should use tabs where possible
#254: FILE: mm/shmem.c:2439:
+^I       ^Istruct folio **foliop, enum sgp_type sgp)$

WARNING: please, no space before tabs
#254: FILE: mm/shmem.c:2439:
+^I       ^Istruct folio **foliop, enum sgp_type sgp)$

total: 2 errors, 2 warnings, 263 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mmtmpfs-consider-end-of-file-write-in-shmem_is_huge.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Rik van Riel <riel@surriel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>