mm-vma-the-pgoff-is-correct-if-can_merge_right-fix
remove now-unused local

mm/vma.c: In function 'vma_merge_new_range':
mm/vma.c:965:23: error: unused variable 'start' [-Werror=unused-variable]
  965 |         unsigned long start = vmg->start;
      |                       ^~~~~
Cc: Jann Horn <jannh@google.com>
Cc: Liam R. Howlett <Liam.Howlett@oracle.com>
Cc: Lorenzo Stoakes <lorenzo.stoakes@oracle.com>
Cc: Vlastimil Babka <vbabka@suse.cz>
Cc: Wei Yang <richard.weiyang@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>