mark-stuff-as-__ro_after_init-checkpatch-fixes
ERROR: "foo * bar" should be "foo *bar"
#52: FILE: block/bdev.c:295:
+static struct kmem_cache * bdev_cachep __ro_after_init;

total: 1 errors, 0 warnings, 383 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mark-stuff-as-__ro_after_init.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Alexey Dobriyan <adobriyan@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>