mm-selftests-add-a-test-to-verify-mmap_changing-race-with-eagain-checkpatch-fixes
WARNING: do not add new typedefs
#86: FILE: tools/testing/selftests/mm/uffd-unit-tests.c:1284:
+typedef enum {

WARNING: braces {} are not necessary for single statement blocks
#106: FILE: tools/testing/selftests/mm/uffd-unit-tests.c:1304:
+	if (!fp) {
+		return THR_STATE_UNKNOWN;
+	}

WARNING: Use of volatile is usually wrong: see Documentation/process/volatile-considered-harmful.rst
#135: FILE: tools/testing/selftests/mm/uffd-unit-tests.c:1333:
+	volatile pid_t *pid = opaque;

ERROR: trailing statements should be on next line
#154: FILE: tools/testing/selftests/mm/uffd-unit-tests.c:1352:
+	while (uffd_read_msg(fd, &msg));

WARNING: Use of volatile is usually wrong: see Documentation/process/volatile-considered-harmful.rst
#180: FILE: tools/testing/selftests/mm/uffd-unit-tests.c:1378:
+	while (!(volatile pid_t)pid)

total: 1 errors, 4 warnings, 215 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-selftests-add-a-test-to-verify-mmap_changing-race-with-eagain.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Peter Xu <peterx@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>