notifiers-add-tracepoints-to-the-notifiers-infrastructure-checkpatch-fixes
ERROR: "(foo*)" should be "(foo *)"
#117: FILE: kernel/notifier.c:43:
+	trace_notifiers_register((void*)n->notifier_call);

ERROR: "(foo*)" should be "(foo *)"
#125: FILE: kernel/notifier.c:53:
+			trace_notifiers_unregister((void*)n->notifier_call);

ERROR: "(foo*)" should be "(foo *)"
#133: FILE: kernel/notifier.c:92:
+		trace_notifiers_run((void*)nb->notifier_call);

total: 3 errors, 0 warnings, 99 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/notifiers-add-tracepoints-to-the-notifiers-infrastructure.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: "Guilherme G. Piccoli" <gpiccoli@igalia.com>
Cc: Guilherme G. Piccoli <kernel@gpiccoli.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>